@startuml
set namespaceSeparator ::
!include mepcore_modules.iuml
!include mepgenetic_modules.iuml

    Object <|-- Gene
    Object <|-- Chromosome
    Object .up. mep::uint: score_
    Object .up. mep::uint: id_

    Chromosome o-- Chromosome::Gene: genes_: vector

    Chromosome::Gene o-down- GenePtr: node

    Gene <|-- FunctionGene
    Gene <|-- TerminalGene
    Gene .. mep::uint: nArgs_
    Gene .. GenePtr: clone()

    TerminalGene <|-- Tree
    FunctionGene o-- mep::FunctionPtr

    Tree o-- Node: root_

    Node o-up- GenePtr: gene_
    Node o-- Node: children

    Object .. Generator

    Object .. Fitness

    Population o-right- Chromosome: population: vector
    Population o-- Fitness: fitness_
    Population o-- Generator
    Population o-up- GeneticSelection
    Population o-up- GeneticOperationGenerator
    Population .up. mep::uint: size_
    Fitness .up. mep::uint: measure()
    Generator o-- mep::FunctionPtr

    GeneticOperationGenerator o-- GeneticOperation

    Object -[hidden]left- GeneticOperation
    Object -[hidden]left- GeneticSelection
    TerminalGene -[hidden]right- FunctionGene
    Chromosome -[hidden]left- Fitness

@enduml